---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
   - name: add_MYUSER
     user: name=MYUSER shell=/bin/bash uid=1001 createhome=yes comment="RCadmin" home=/home/MYUSER
   - name: add_MYUSER2sudo
     lineinfile: "dest=/etc/sudoers
       insertafter=EOF
       line='MYUSER ALL=(ALL) NOPASSWD: ALL'"
     become: yes
     become_method: sudo
   
   - name: create_ssh_dir
     file: path=/home/MYUSER/.ssh state=directory
        owner=MYUSER group=MYUSER mode=0700

   - name: upload_pubkey
     template: src=../.keys/authorized_keys
        dest=/home/MYUSER/.ssh/authorized_keys
        owner=MYUSER group=MYUSER mode=0600

   - name: upload_pemkey_asRSA
     template: src=../.keys/rci.pem
        dest=/home/MYUSER/.ssh/id_rsa.pub
        owner=MYUSER group=MYUSER mode=0600

   - name: upload_pemkey_asDSA
     template: src=../.keys/rci.pem
        dest=/home/MYUSER/.ssh/id_dsa.pub
        owner=MYUSER group=MYUSER mode=0600
