---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
   - name: nmap
     apt: name=nmap state=present install_recommends=yes 
   - name: tcpdump
     apt: name=tcpdump state=present install_recommends=yes 
