# ansible-playbook -e "hostgroups=foo ... groupname=$GROUPNAME" groupdel.yml
---
- hosts: "{{ hostgroups }}"
  become: yes
  become_method: sudo
  vars:
   delgroup: "{{ groupname }}"
  tasks:
   - name: delgroup
     group:
       name: "{{ delgroup }}"
       state: absent

