# This is a good one for HPC
---
- hosts: "{{ hostgroups }}"
  become: yes
  become_method: sudo
  tasks:
   - name: set_filemax
     command: "echo 78877555 > /proc/sys/fs/file-max"
   - name: restart_sysctl
     command: "/sbin/sysctl -p"

