#!/usr/bin/python3
# This is an example of printing from elastisearch
# to make it useful, a shell wrapper that passes the following:
#    index_name, doc_id  
from elasticsearch import Elasticsearch, RequestsHttpConnection
from requests_aws4auth import AWS4Auth
import boto3
# For example, my-test-domain.us-east-1.es.amazonaws.com
# A more realistic example:
 host = 'search-zaphod-someguuid.us-east-1.es.amazonaws.com'
# e.g. us-west-1
region = 'us-east-1' 

service = 'es'
credentials = boto3.Session().get_credentials()
awsauth = AWS4Auth(credentials.access_key, credentials.secret_key, region, service, session_token=credentials.token)

es = Elasticsearch(
    hosts = [{'host': host, 'port': 443}],
    http_auth = awsauth,
    use_ssl = True,
    verify_certs = True,
    connection_class = RequestsHttpConnection
)

print(es.get(index="tutorials", doc_type="_doc", id="3"))

