# -e "hostgroups=foo bar ..."
---
- hosts: "{{ hostgroups }}"
  become: yes
  become_method: sudo
  tasks:
   - name: cache_update
     apt:
       update_cache: yes

   - name: upgrade
     apt: 
       upgrade: dist

