# -e "hostgroups=foo bar ... "
---
- hosts: "{{ hostgroups }}"
  become: yes
  become_method: sudo
  tasks:
   - copy:
      src: ../files/etc_sudoersd_docker
      dest: /etc/sudoers.d/docker
      owner: root
      group: root
      mode: 0440

