#  -e "hostgroups=foo"
---
- hosts: "{{ hostgroups }}"
  become: yes
  become_method: sudo
  vars:
   src_path: 10.0.100.10:/opt
   mnt_path: /opt
  tasks:
  - name: Mount NFS
    mount: name=/opt src="{{ src_path }}" fstype=nfs opts=rw,nfsvers=3,intr,timeo=14,nolock,noatime,noacl,sec=sys,proto=tcp state=mounted
