# ansible-playbook -e "hostgroups=bar username=$USER groupname=$GROUP  usergroup.yml
---
- hosts: "{{ hostgroups }}"
  become: yes
  become_method: sudo
  vars:
   userlogin: "{{ username }}"
   usrgroup: "{{ groupname }}"
  tasks:
   - name: Add "{{ userlogin }}" to group "{{ usrgroup }}"
     user:
       name: "{{ userlogin }}"
       groups: "{{ usrgroup }}"
       append: yes

