# ansible-playbook -u [ubuntu|centos|redhat] -e "username=ar6 hostgroups=foo" userdel.yml
---
- hosts: "{{ hostgroups }}"
  become: yes
  become_method: sudo
  vars:
   deluserlogin: "{{ username }}"

