# ansible-playbook  -e "hostgroups=foo username=ar6" userdel.yml
---
- hosts: "{{ hostgroups }}"
  become: yes
  become_method: sudo
  vars:
   deluserlogin: "{{ username }}"
  tasks:
   - name: deluser
     user:
       name: "{{ deluserlogin }}"
       state: absent
       remove: yes
